### ISSUE TITLE
why not use the real API? 

### ISSUE THREAD

**Issue by splitbrain** [krowvin/dokurestapi#1]
Just a heads up, there is a proper API that you can use instead of this. https://www.dokuwiki.org/devel:remote_api

**Comment by krowvin** [comment]
I looked around on GitHub to try and find a python wrapper for any of the official or even unofficial API to doku. 

I found [dokuwiki](https://python-dokuwiki.readthedocs.io/en/latest/) and [python-dokuwiki](https://github.com/fmenabe/python-dokuwiki) but neither seemed to expose the users (which I needed for my current project)

I also looked into the RPC docs and honestly don't know a ton about it. Decided to just reverse engineer the existing HTTP calls. Seems I could still just use those RPC calls now and update. But looking at the docs now that I've been called out I see [these calls](https://www.dokuwiki.org/lib/exe/openapi.php#?route=overview) which don't seem to include get all current users, bulk submit a user import,etc. I have this implemented to some degree now. 

Seeing as I created a PyPi package for this I'm sure you're at least a little annoyed. It certainly crossed my mind that the second you change one of those undocumented endpoints it would break what I've done and that could lead to potential users blaming your side. The entire reason they aren't documented is so you can do that. 

(I thought about pairing the tags to the version of doku this works with though)


All this to say, I am using this and just thought to share! The end-user wouldn't know the difference on how the calls are made since it's a wrapper.
